imports:
    - { resource: parameters.yml }
    - { resource: doctrine.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: solarium.yml }
#    - { resource: aws.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


# REST Configuration
fos_rest:
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: force
    routing_loader:
        default_format: json
#    service:
#        inflector: misa.inflector.service
#    serializer:
#        serialize_null: false
    access_denied_listener:
        json: true
    exception:
        enabled: true
        codes:
            Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException : 300
            Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException : 301
            MisaSdk\Common\Exception\BadRequest : 400
            FOS\RestBundle\Exception\InvalidParameterException: 200
        messages:
            Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: true
            Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: true
            MisaSdk\Common\Exception\BadRequest : true
