# Doctrine Configuration

doctrine:
    dbal:
        driver: pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        metadata_cache_driver:
            type: memcached
            host: "%memcached_host%"
            port: "%memcached_port%"
            instance_class: Memcached
            class: Doctrine\Common\Cache\MemcacheCache
        query_cache_driver:
            type: memcached
            host: "%memcached_host%"
            port: "%memcached_port%"
            instance_class: Memcached
            class: Doctrine\Common\Cache\MemcacheCache
        result_cache_driver:
            type: memcached
            host: "%memcached_host%"
            port: "%memcached_port%"
            instance_class: Memcached
            class: Doctrine\Common\Cache\MemcacheCache
        second_level_cache:
            enabled:  true
            log_enabled: true

        mappings:
            accounting:
                is_bundle: false
                mapping: true
                type: yml
                dir:  "%kernel.root_dir%/../src/Accounting/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: Misa\Accounting\Domain
                alias: Accounting

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: App\Migrations
    table_name: migration_versions
    name: Application Migrations