# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            users:
                is_bundle: false
                mapping: true
                type: yml
                dir:  "%kernel.root_dir%/../src/Users/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: Misa\Users\Domain
                alias: Users

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: App\Migrations
    table_name: migration_versions
    name: Application Migrations