location:
    type:     annotation
    prefix:   "v1/location"
    resource: "@LocationBundle/Controller/"

accounting:
    type:     annotation
    prefix:   "v1/accounting"
    resource: "@AccountingBundle/Controller/"
