nelmio_solarium:
    endpoints:
        provider:
            scheme: http
            host: '%solr.client.host%'
            port: '%solr.client.port%'
            path: '%solr.client.path%'
            timeout: '%solr.client.timeout%'
            core: provider
    clients:
        provider:
            endpoints: [provider]