services:

    _defaults:
        autowire: true
        autoconfigure: true

    Misa\Accounting\Infrastructure\Ui\AccountingBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    ###  event
    Misa\Accounting\Application\Event\Provider\MngEvent: ~
    Misa\Accounting\Application\Event\Company\MngEvent: ~

    ###    services
    #provider
    Misa\Accounting\Application\Services\Provider\MngService: ~
    Misa\Accounting\Application\Services\Provider\ListService: ~
    Misa\Accounting\Application\Services\Provider\SearchService: ~
    #provider info
    Misa\Accounting\Application\Services\Provider\Information\EmailService: ~

    #provider
    Misa\Accounting\Application\Services\Source\MngService: ~
    Misa\Accounting\Application\Services\Source\SearchService: ~


    ###   repository
    #persistence provider
    Misa\Accounting\Domain\Provider\BankDetail\BankRepository: '@accounting.doctrine.provider.bank'
    Misa\Accounting\Domain\Product\ProductRepository: '@accounting.doctrine.product'
    Misa\Accounting\Domain\Product\ItemRepository: '@accounting.doctrine.product.item'
    Misa\Accounting\Domain\Provider\ProviderRepository: '@accounting.doctrine.provider'
    Misa\Accounting\Domain\Provider\Information\EmailRepository: '@accounting.doctrine.provider.email'
    Misa\Accounting\Domain\Provider\Information\PhoneRepository: '@accounting.doctrine.provider.phone'
    Misa\Accounting\Domain\Provider\BankDetail\BankAccountRepository: '@accounting.doctrine.provider.bankaccount'
    #searchEngine
    Misa\Accounting\Domain\Provider\ProviderSearchRepository: '@accounting.solr.provider.search'
    Misa\Accounting\Domain\Provider\Source\SearchRepository: '@accounting.solr.company.search'

    #persistence source
    Misa\Accounting\Domain\Provider\Source\SourceRepository: '@accounting.doctrine.source'

    accounting.doctrine.provider.bank:
        class: Misa\Accounting\Infrastructure\Persistence\Doctrine\ProviderBankDoctrineRepository
        arguments: { $entityName: 'Misa\Accounting\Domain\Provider\BankDetail\Bank' }

    accounting.doctrine.provider.email:
        class: Misa\Accounting\Infrastructure\Persistence\Doctrine\ProviderEmailDoctrineRepository
        arguments: { $entityName: 'Misa\Accounting\Domain\Provider\Information\Email' }

    accounting.doctrine.provider.bankaccount:
        class: Misa\Accounting\Infrastructure\Persistence\Doctrine\ProviderBankAccountDoctrineRepository
        arguments: { $entityName: 'Misa\Accounting\Domain\Provider\BankDetail\BankAccount' }

    accounting.doctrine.provider.phone:
        class: Misa\Accounting\Infrastructure\Persistence\Doctrine\ProviderPhoneDoctrineRepository
        arguments: { $entityName: 'Misa\Accounting\Domain\Provider\Information\Phone' }

    accounting.doctrine.product:
        class: Misa\Accounting\Infrastructure\Persistence\Doctrine\ProductDoctrineRepository
        arguments: {$entityName: 'Misa\Accounting\Domain\Product\Product'}

    accounting.doctrine.product.item:
        class: Misa\Accounting\Infrastructure\Persistence\Doctrine\ProductItemRepository
        arguments: {$entityName: 'Misa\Accounting\Domain\Product\Item'}

    accounting.doctrine.provider:
        class: Misa\Accounting\Infrastructure\Persistence\Doctrine\ProviderDoctrineRepository
        arguments: {$entityName: 'Misa\Accounting\Domain\Provider\Provider'}

    accounting.doctrine.source:
        class: Misa\Accounting\Infrastructure\Persistence\Doctrine\SourceDoctrineRepository
        arguments: {$entityName: 'Misa\Accounting\Domain\Provider\Source\Source'}

    accounting.solr.provider.search:
        class: Misa\Accounting\Infrastructure\SearchEngine\Solr\ProviderSolrRepository
        arguments: ['@solarium.client.provider']

    accounting.solr.company.search:
        class: Misa\Accounting\Infrastructure\SearchEngine\Solr\CompanySolrRepository
        arguments: ['@solarium.client.company']