version: '2'
services:

  cli:
    image: jguillermo/alpine-php:cli
    environment:
       - DEV_UID=${DEV_UID}
       - DEV_GID=${DEV_GID}
    volumes:
       - ./app/:/var/www/html
       - ./docker/ssh/:/app/.ssh/
