version: '2'
services:

  php:
      image: jguillermo/misa-accounting:php
      volumes:
        - ./app/:/var/www/html
      ports:
        - 8085:80
      depends_on:
         - mysql

  mysql:
    image: jguillermo/misa-accounting:mysql
    environment:
      MYSQL_ROOT_PASSWORD: toord
      MYSQL_USER : root
      MYSQL_DATABASE: dbproject
    ports:
      - 3369:3306
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d

  memcached:
    image: memcached:alpine
    ports:
      - 11211:11211

  cli:
    image: jguillermo/misa-accounting:cli
    environment:
       - DEV_UID=${DEV_UID}
       - DEV_GID=${DEV_GID}
    volumes:
       - ./app/:/var/www/html
       - ./docker/ssh/:/app/.ssh/
    depends_on:
       - php
       - mysql
    command: ["/tmp/wait-for-it.sh", "mysql:3305", "--", "composer integration-test"]