version: '2'
services:
  cli:
    image: jguillermo/misa-accounting:cli
    environment:
        - DEV_UID=${DEV_UID}
        - DEV_GID=${DEV_GID}
    volumes:
        - ./app/:/var/www/html
        - ./docker/ssh/:/app/.ssh/
#    command: composer update --no-progress --profile --prefer-dist

