version: '2'
services:

  php:
    extends:
      file: docker-compose.yml
      service: php

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql

  memcached:
    extends:
      file: docker-compose.yml
      service: memcached

  solr:
    extends:
      file: docker-compose.yml
      service: solr

  cli:
    image: jguillermo/api-test:latest
    volumes:
      - ./app/tests/e2e:/app/e2e
    depends_on:
       - php
       - mysql
       - memcached
       - solr
    command: "/tmp/wait-for-it.sh mysql:3306 -t 50 -- npm test"
