version: '2'
services:

  php:
      image: jguillermo/alpine-php:nginx
      volumes:
        - ./app/:/var/www/html
        - ./log/:/var/log/nginx/
      ports:
        - 8085:80

  mysql:
    image: jguillermo/docker-persist:mysql
    environment:
      MYSQL_ROOT_PASSWORD: toord
      MYSQL_USER : root
      MYSQL_DATABASE: dbproject
    ports:
      - 3369:3306
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d

  memcached:
    image: memcached:alpine
    ports:
      - 11211:11211

  solr:
    image: jguillermo/docker-persist:solr
    ports:
      - 8983:8983
    volumes:
      - ./solr:/opt/solr/server/solr/mycores
      - ./app/export:/opt/solr/mydata

    # sudo chmod o+w -R solr
