version: '2'
services:

  php:
    extends:
      file: docker-compose.yml
      service: php

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql

  memcached:
    extends:
      file: docker-compose.yml
      service: memcached

  solr:
    extends:
      file: docker-compose.yml
      service: solr

  cli:
    extends:
      file: docker-compose.tasks.yml
      service: cli
    depends_on:
       - php
       - mysql
       - memcached
       - solr
    command: ["/tmp/wait-for-it.sh --timeout=50 mysql:3306", "--", "composer integration-test"]