nelmio_solarium:
    endpoints:
        provider:
            scheme: http
            host: '%solr.client.host%'
            port: '%solr.client.port%'
            path: '%solr.client.path%'
            timeout: '%solr.client.timeout%'
            core: provider
        ubigeo:
            scheme: http
            host: '%solr.client.host%'
            port: '%solr.client.port%'
            path: '%solr.client.path%'
            timeout: '%solr.client.timeout%'
            core: ubigeo
        company:
            scheme: http
            host: '%solr.client.host%'
            port: '%solr.client.port%'
            path: '%solr.client.path%'
            timeout: '%solr.client.timeout%'
            core: company
        product:
            scheme: http
            host: '%solr.client.host%'
            port: '%solr.client.port%'
            path: '%solr.client.path%'
            timeout: '%solr.client.timeout%'
            core: product
    clients:
        provider:
            endpoints: [provider]
        ubigeo:
            endpoints: [ubigeo]
        company:
            endpoints: [company]
        product:
            endpoints: [product]