Misa\Accounting\Domain\Payment\Type:
    type: entity
    table: payment_type
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: NONE
    fields:
        description:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
